# Generated by Django 5.1.4 on 2024-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_uploadedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image',
            new_name='original_image',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='formatted_image',
            field=models.ImageField(blank=True, null=True, upload_to='formatted_uploads/'),
        ),
    ]
