# Generated by Django 5.1.4 on 2024-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_uploadedimage_formatted_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='formatted_image',
            field=models.ImageField(blank=True, null=True, upload_to='formatted_uploads/'),
        ),
    ]
